### ISSUE TITLE
What ML model works best?

### ISSUE THREAD

**Issue by alyoshenka** [itsjpb/470-avalanche-prediction#36]
## What data model(s) is best suited to our needs? 
"Random Forest Model would be a good starting point. Feel free to explore other models as well (ex. gradient boosting, linear model, support vector machines, etc)" -BC

**Comment by Ladybird91** [comment]
https://docs.google.com/document/d/19UnRkW-gWVjOWSk2-YzcHqdsUt9YW9NfKujpAW1ApMk/edit

**Comment by Ladybird91** [comment]
Updated Document on plan of action for ML model: https://docs.google.com/document/d/11GF6xGNWtzD1K06WQD_8VWYVnSZAmdbt3vClf62FPn0/edit
